name: Deploy CloudFormation Stack
on:
  push:
    branches:
      - backend-demo-vinayak
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Upload index.mjs to S3
      run: |
        aws s3 cp ./index.mjs s3://demos3forcrud/index.mjs

    - name: Package CloudFormation Template
      run: |
        aws cloudformation package \
          --template-file CRUD.yaml \
          --s3-bucket demos3forcrud \
          --output-template-file packaged-template.yaml

    - name: Deploy CloudFormation stack 
      run: |
        aws cloudformation deploy \
          --template-file CRUD.yaml \
          --stack-name VinayakCloudFormation \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Describe CloudFormation stack
      if: ${{ failure() }}
      run: |
        aws cloudformation describe-stack-events \
          --stack-name VinayakCloudFormation
